

 
 
CREATE TABLE AccountType(
    ACCOUNT_TYPE_ID NUMBER(15),
    MNEMONIC VARCHAR(50) NOT NULL,
    ACCOUNT_TYPE_NAME VARCHAR(50) NOT NULL,
    CREATION_DATE DATE,
    CONSTRAINT Account_Type_Pk primary key (ACCOUNT_TYPE_ID)
    );

CREATE TABLE AccountTransaction(
    
    ACCOUNT_TRA_ID NUMBER(15),
    ACCOUNT_TYPE_ID NUMBER(15) REFERENCES AccountType(ACCOUNT_TYPE_ID),
    MEMBER_ID NUMBER(15),
    AMOUNT NUMBER(6),
    TRANSACTION_DATE DATE,
    CONSTRAINT Account_TR_ID primary key(ACCOUNT_TYPE_ID)
    );